[package]
name = "supply-stacks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
advent-utils = { path = "../advent-utils" }
regex = "1.7.0"
